# Generated by Django 2.2.5 on 2020-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainno', models.CharField(max_length=6)),
                ('trainname', models.CharField(max_length=50)),
                ('ac2tier', models.CharField(max_length=30)),
                ('ac3tier', models.CharField(max_length=30)),
                ('sleeper', models.CharField(max_length=30)),
            ],
        ),
    ]
