# Generated by Django 2.2.5 on 2020-03-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0003_trainroute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainroute',
            new_name='TrainrouteData',
        ),
    ]
