# Generated by Django 2.2.5 on 2020-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0005_passengerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcdata',
            name='mobile',
            field=models.CharField(default='', max_length=30),
        ),
    ]
