# Generated by Django 2.2.5 on 2020-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0006_tcdata_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdata',
            name='doj',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='idproof',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='trainid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
