# Generated by Django 2.2.5 on 2020-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0007_auto_20200613_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdata',
            name='destination',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='source',
            field=models.CharField(default='', max_length=30),
        ),
    ]
