# Generated by Django 2.2.5 on 2020-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0008_auto_20200613_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdata',
            name='coachtype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
