# Generated by Django 2.2.5 on 2020-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0009_passengerdata_coachtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdata',
            name='coachtype',
            field=models.CharField(default='2 Tire AC', max_length=30),
        ),
    ]
