# Generated by Django 2.2.5 on 2020-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0011_auto_20200614_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdata',
            name='pnrnumber',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='statusnumber',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='ticketkey',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='ttapproval',
            field=models.CharField(default='', max_length=30),
        ),
    ]
