# Generated by Django 2.2.5 on 2020-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0012_auto_20200814_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcdata',
            name='mobile',
            field=models.CharField(default='9845356246', max_length=30),
        ),
    ]
