# Generated by Django 2.2.5 on 2020-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAILWAYAPP', '0013_auto_20200824_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcdata',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
